### PR TITLE
VisUI version changed to the latest stable release.

### PR DESCRIPTION
**Pull request by metaphore**
Sorry, had to spam another PR as the previous one doesn't reflect this commit.

@czyzby, if there is no CI for snapshots, I'm afraid I have to ask you to publish Maven artifacts once again, hope that's not a lot of a trouble.

Thanks!

### CODE REVIEW

**Comment by czyzby** [comment]
It's OK, thanks for the update!

**Comment by metaphore** [comment]
@czyzby hm, I cannot find the latest snapshot release, is it not published yet?

https://oss.sonatype.org/content/repositories/snapshots/com/github/czyzby/gdx-lml/

**Comment by czyzby** [comment]
I'll clean, rebuild and reupload.

**Comment by metaphore** [comment]
@czyzby guess what? 😃 
The last uploaded snapshot jar seems to be broken. There is nothing inside but `META-INF`.

Check out the size of `gdx-lml-1.9.1.9.10-20190816.082017-7.jar` in here
https://oss.sonatype.org/content/repositories/snapshots/com/github/czyzby/gdx-lml/1.9.1.9.10-SNAPSHOT/

**Comment by czyzby** [comment]
Sonatype was acting weird and throwing 503s, might have been related. Well, I'll try to reupload again.

**Pull request merged**
