### PR TITLE
Fix unexpected duplicate component creation in "processDelayedConstructions()"

### PR DESCRIPTION
**Pull request by XIII-th**
…or()"

to avoid duplicate component initialisation in "processDelayedConstructions()"

### CODE REVIEW

**Comment by czyzby** [comment]
I appreciate these fixes, thanks.

Can you provide a simple reproducible example of an application that causes the issue?

**Comment by XIII-th** [comment]
Exemple is ready. Download [this archive](https://github.com/czyzby/gdx-lml/files/1503789/pull.request.XIII-th.zip) and looking for comments in `DesktopLauncher` class

**Comment by czyzby** [comment]
Thanks, I'll look into the issue this week. I'll also try my best to upload the updated libraries (I'm currently between jobs, and I didn't have much time for open source last week, sorry).

**Comment by czyzby** [comment]
Not a fan of extending `addIfNotNull` (a simple utility) with a `Constructor` parameter. I'll address the issue with a similar solution, but I'm closing this merge request. Expect a snapshot release soon. Thanks.

**Comment by czyzby** [comment]
Actually, I'll just refactor the problematic bit. Thanks again.

**Pull request merged**
